# It fetches my github contirubiont counts and pushes it to a gcp bucket so that it can be shown as particles on my landing site www.yogeshdrall.in
 
name:
  Contribution Count Cron Job
 
  # Controls when the workflow will run
# on:
#   # Triggers the workflow every 5 minutes
#   schedule:
#     - cron: "0 * * * *" 

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  schedule:
    - cron: "0 1 * * *" 

jobs:
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            ref: main
      - name: Checkout code
        uses: octokit/graphql-action@v2.x
        id: get_contribution_count
        with:
          query: query {viewer {contributionsCollection {contributionCalendar {totalContributions}}}}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Update github contribution data
        uses: jossef/action-set-json-field@v2.1
        with:
          file: config.json
          field: contrib
          value: ${{ steps.get_contribution_count.outputs.data }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit --allow-empty -m "cron: udpating github contributions"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: main

