# It fetches my github contirubiont counts and pushes it to a gcp bucket so that it can be shown as particles on my landing site www.yogeshdrall.in
 
name:
  Contribution Count Cron Job
 
  # Controls when the workflow will run
# on:
#   # Triggers the workflow every 5 minutes
#   schedule:
#     - cron: "0 * * * *" 

on:
  push:
    branches:
      - main
jobs:
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_contribution_count
        with:
          query: query {viewer {contributionsCollection {contributionCalendar {totalContributions}}}}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Update my-file.json description
        uses: jossef/action-set-json-field@v2.1
        with:
          file: config.json
          field: contrib
          value: ${{ steps.get_contribution_count.outputs.data }}
